// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1xqacoQ_f7Oh3ScC4KaoXuOiirF3PAzM',
    appId: '1:596595019913:web:47d10b576c1737542ef658',
    messagingSenderId: '596595019913',
    projectId: 'qrdoorbell-v1',
    authDomain: 'qrdoorbell-v1.firebaseapp.com',
    storageBucket: 'qrdoorbell-v1.appspot.com',
    measurementId: 'G-BER8W6T7WE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuGjOjsX3sAfpQsqK8hH3o1JxrA3dXq7M',
    appId: '1:596595019913:android:b9fb80d17fe257b82ef658',
    messagingSenderId: '596595019913',
    projectId: 'qrdoorbell-v1',
    storageBucket: 'qrdoorbell-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVBruJnxt4zW0Eqlg7JtLVvotnSSiz8UI',
    appId: '1:596595019913:ios:4691deb1dd92bd3e2ef658',
    messagingSenderId: '596595019913',
    projectId: 'qrdoorbell-v1',
    storageBucket: 'qrdoorbell-v1.appspot.com',
    iosClientId: '596595019913-pbf9itq8j5b15v06gq5l1oj1sira0231.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrdoorbellMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVBruJnxt4zW0Eqlg7JtLVvotnSSiz8UI',
    appId: '1:596595019913:ios:4691deb1dd92bd3e2ef658',
    messagingSenderId: '596595019913',
    projectId: 'qrdoorbell-v1',
    storageBucket: 'qrdoorbell-v1.appspot.com',
    iosClientId: '596595019913-pbf9itq8j5b15v06gq5l1oj1sira0231.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrdoorbellMobile',
  );
}
